CREATE TABLE `USERS` (
    `ID` INTEGER PRIMARY KEY AUTOINCREMENT,
    `NAME` TEXT NOT NULL,
    `PASSWORD` TEXT NOT NULL,
    `ROLE` TEXT NOT NULL,
    `BIO` TEXT
);

CREATE TABLE `RX_PACKET` (
    `ID` INTEGER PRIMARY KEY AUTOINCREMENT,
    `TIMESTAMP` TEXT NOT NULL,
    `TYPE` TEXT NOT NULL,
    `CHANNEL` INTEGER NOT NULL,
    `DIAL` INTEGER NOT NULL,
    `FREQ` INTEGER NOT NULL,
    `OFFSET` INTEGER NOT NULL,
    `SNR` INTEGER NOT NULL,
    `MODE` TEXT NOT NULL,
    `TIME_DRIFT` INTEGER NOT NULL,
    `GRID` TEXT,
    `FROM` TEXT,
    `TO` TEXT,
    `TEXT` TEXT NOT NULL,
    `COMMAND` TEXT,
    `EXTRA` TEXT
);

CREATE INDEX RX_PACKET_DAY_IDX ON `RX_PACKET`(date(`TIMESTAMP`));

CREATE TABLE `RX_SPOT` (
    `ID` INTEGER PRIMARY KEY AUTOINCREMENT,
    `TIMESTAMP` TEXT NOT NULL,
    `CALL` TEXT,
    `GRID` TEXT,
    `SNR` INTEGER NOT NULL,
    `CHANNEL` INTEGER NOT NULL,
    `DIAL` INTEGER NOT NULL,
    `FREQ` INTEGER NOT NULL,
    `OFFSET` INTEGER NOT NULL
);

CREATE INDEX RX_SPOT_DAY_IDX ON `RX_SPOT`(date(`TIMESTAMP`));

CREATE TABLE `TX_FRAME` (
    `ID` INTEGER PRIMARY KEY AUTOINCREMENT,
    `TIMESTAMP` TEXT NOT NULL,
    `CHANNEL` INTEGER,
    `DIAL` INTEGER,
    `FREQ` INTEGER,
    `OFFSET` INTEGER,
    `MODE` TEXT, 
    `SPEED` TEXT, 
    `SELECTED` TEXT,
    `TONES` TEXT
);

CREATE INDEX TX_FRAME_DAY_IDX ON `TX_FRAME`(date(`TIMESTAMP`));


CREATE TABLE `STATION_INFO` (
    `ID` INTEGER PRIMARY KEY AUTOINCREMENT,
    `TIMESTAMP` TEXT NOT NULL,
    `LATEST` INTEGER,
    `CALL` TEXT,
    `GRID` TEXT,
    `INFO` TEXT,
    `STATUS` TEXT
);

CREATE INDEX STATION_INFO_STATUS_IDX ON `STATION_INFO`(`LATEST`) WHERE `LATEST` = 1;
