CREATE TABLE `USERS` (
    `ID` INTEGER PRIMARY KEY AUTOINCREMENT,
    `NAME` TEXT NOT NULL,
    `PASSWORD` TEXT NOT NULL,
    `ROLE` TEXT NOT NULL,
    `BIO` TEXT
);

CREATE TABLE `RX_PACKETS` (
    `ID` INTEGER PRIMARY KEY AUTOINCREMENT,
    `TYPE` TEXT NOT NULL,
    `CHANNEL` INTEGER NOT NULL,
    `DIAL` INTEGER NOT NULL,
    `FREQ` INTEGER NOT NULL,
    `OFFSET` INTEGER NOT NULL,
    `SNR` INTEGER NOT NULL,
    `MODE` TEXT NOT NULL,
    `TIME_DRIFT` INTEGER NOT NULL,
    `GRID` TEXT,
    `FROM` TEXT,
    `TO` TEXT,
    `TEXT` TEXT NOT NULL,
    `COMMAND` TEXT,
    `EXTRA` TEXT
);

CREATE TABLE `RX_SPOTS` (
    `ID` INTEGER PRIMARY KEY AUTOINCREMENT,
    `CALL` TEXT,
    `GRID` TEXT,
    `SNR` INTEGER NOT NULL,
    `CHANNEL` INTEGER NOT NULL,
    `DIAL` INTEGER NOT NULL,
    `FREQ` INTEGER NOT NULL,
    `OFFSET` INTEGER NOT NULL
 );


